pub mod adms;
pub mod alloc;
pub mod analytics;
pub mod batch;
pub mod benchmark;
pub mod completions;
pub mod convert;
pub mod datasets;
pub mod derms;
pub mod dist;
pub mod doctor;
pub mod featurize;
pub mod geo;
pub mod graph;
#[cfg(feature = "gui")]
pub mod gui;
pub mod import;
pub mod inspect;
pub mod nminus1;
pub mod opf;
pub mod pf;
pub mod runs;
pub mod scenarios;
pub mod se;
pub mod solver;
pub mod telemetry;
pub mod tep;
pub mod ts;
#[cfg(feature = "tui")]
pub mod tui;
pub mod util;
pub mod validate;
pub mod version;
#[cfg(feature = "viz")]
pub mod viz;
